apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-test
  namespace: default
spec:
  action: delay
  mode: all
  selector:
    namespaces:
      - default
  delay:
    latency: "200ms"
  duration: "2m"
