clusters:
  - name: cluster2
    context: cluster2
    tier: dev
    namespaces:
      - '*'
  - name: local-cluster
    context: minikube
    tier: dev
    namespaces:
      - '*'
  - name: staging-cluster
    context: staging-cluster
    tier: staging
    namespaces:
      - '*'
